### ISSUE TITLE
Unable to install Scipy on new machine

### ISSUE THREAD

**Issue by seamuss1** [dpploy/cortix#129]
An additional library is needed to install the Scipy requirement:
`sudo apt-get install libatlas-base-dev gfortran`
Perhaps this step can be added to the Cortix README.

**Comment by tazzaoui** [comment]
When a dependency is listed, it is assumed that its dependencies must also be installed. Otherwise, the README will be cluttered with information that does not really pertain to Cortix.

**Comment by seamuss1** [comment]
Ok thank you. 
This was on a fresh Raspian install on the Raspberry Pi 3 B+.

**Comment by seamuss1** [comment]
Having trouble completing a pip install for Scipy on the Pi.
The solution is to .whl file directly and use that for the install:
https://raspberrypi.stackexchange.com/questions/8308/how-to-install-latest-scipy-version-on-raspberry-pi
