### ISSUE TITLE
Droplet DataFrame output

### ISSUE THREAD

**Issue by seamuss1** [dpploy/cortix#139]
For the droplet example in console-run, can the output data be changed to CSV format? This would make parsing the file easier before moving on to true message passing. 
I suggest incorporating these methods into the code:
`pandas.to_csv()`
`pandas.read_csv()`

**Comment by tazzaoui** [comment]
CSV as opposed to XML? I'm open to the idea, but `state.xml` seems to be deeply embedded into the module structure. Thoughts @dealmeidavf ?

**Comment by tazzaoui** [comment]
Closing this due to no response
