### ISSUE TITLE
Add an ID# to the end of file names

### ISSUE THREAD

**Issue by seamuss1** [dpploy/cortix#149]
Would it be possible to add a unique identifier to the end of files? At the moment it is impossible to distinguish results from different runs. This change would also allow more than 1 results files to exist in the same directory.
Another advantage is improved continuity when having multiple instances running at the same time.
I like to get the ID string from the timestamp:
`datetime.datetime.now()`

**Comment by tazzaoui** [comment]
You mean add a time stamp to the work directory name?

If you're interested in doing this, the logic is in  `cortix_main.py`. Check it out here: https://github.com/dpploy/cortix/blob/master/cortix/src/cortix_main.py#L63

**Comment by tazzaoui** [comment]
Closing this due to no response.
