### ISSUE TITLE
run_droplet structure review

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#161]
I am looking at the flow of a Cortix run [file](https://github.com/dpploy/cortix/blob/3b4b434dd0379f03e8fd5167f02f81c93b06217f/cortix/examples/fluidflow/run_droplet.py#L41-L43). Why 3 ports in a Droplet module? In the same vein. If a port is added to a different droplet object, why does it need an indexed name? why can't it be the same port name since it belongs to a different object? Ah. The indexed ports all go to Vortex. Disregard the indexing but this calls for clarity.

**Comment by tazzaoui** [comment]
Solved in commit `714a76d`
