### ISSUE TITLE
vortex review

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#162]
[Vortex](https://github.com/dpploy/cortix/blob/3b4b434dd0379f03e8fd5167f02f81c93b06217f/cortix/examples/fluidflow/vortex.py#L48-L55) does not need to know about the existence of droplets. This points to a review of how ports are created.

**Comment by tazzaoui** [comment]
Addressed in 714a76d

**Comment by tazzaoui** [comment]
Addressed in 714a76d
