### ISSUE TITLE
should Port do the send and receive directly?

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#166]
[This](https://github.com/dpploy/cortix/blob/99b0c9a5dbaa74af090fae13c1c41ca22ca2db01/cortix/src/module.py#L19-L46) could be eliminated and module developers implement the call to the port directly. The resulting module derived code would be more expressive. For example:

`""" Droplet module """`
[snip]
`port = self.get_port('flow-velocity')`
`port.send( (time,position) )`
`flow_velocity = port.recv()`

Or maybe have a single call?
`flow_velocity = port.send_recv( (time,position) )`

Seems like the send and receive are jobs for Port objects.

**Comment by tazzaoui** [comment]
That's certainly one way to design it. The idea behind `module.send` is to encapsulate the low-level port programming and provide the user with a layer of abstraction.

Calling `port.send` directly is of course possible with the given setup, `module.send` just provides a opaque way to go about sending.
