### ISSUE TITLE
What is the Cortix receive function?

### ISSUE THREAD

**Issue by seamuss1** [dpploy/cortix#169]
There is a send function, where is its opposite function to receive? Has it been implemented yet?
Could it be added in with syntax to match existing socket language?
https://docs.python.org/2/library/socket.html#socket.socket.recv

**Comment by tazzaoui** [comment]
The `recv` function is here: https://github.com/dpploy/cortix/blob/master/cortix/src/module.py#L35. The syntax corresponds to that of sockets with the exception that in sockets you receive a byte string but in Cortix you receive the actual object you sent (pickle magic behind the scenes) so no need to specify the buffer size :)
