### ISSUE TITLE
How to communicate from module to main thread?

### ISSUE THREAD

**Issue by seamuss1** [dpploy/cortix#170]
How do pass a message from a Cortix module to the main thread?
All the examples have modules only communicating with other modules.
I want to start an independent process using a Cortix object, then pass messages to and from that module while it runs indefinitely.

**Comment by dealmeidavf** [comment]
What will the Cortix process be doing?

**Comment by tazzaoui** [comment]
Any updates on this?

**Comment by seamuss1** [comment]
Yes actually. 
I pushed a solution to my branch. It's a worker-type function that spawns a 2 threads to start the task and facilitate communication.
https://github.com/dpploy/cortix/blob/seamus/cortix/src/peon.py

Works great. It's currently in use in DADOS

**Comment by dealmeidavf** [comment]
There may be a need in the future for module processes to communicate with the rank 0 Cortix process (in case of MPI) or vice-versa but we do not want to use threads for this.

**Comment by dealmeidavf** [comment]
I am closing this issue so it does not distract us from other pressing issues that are labeled as `bugs`.
