### ISSUE TITLE
Thread unsafe plotting

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#174]
[This loop](https://github.com/dpploy/cortix/blob/c51f121a33a2b4db84f1cf5408cd019581573693/cortix/util/dataplot.py#L28-L31) seems not to work unless the loop is over one port. Since `Matplotlib` is not thread-safe once these plotting threads are created with plotting functions, the plots do not come out correct. Please verify or correct this. There is a `run_droplet-2.py` cortix run file in `examples/` that runs a problematic case with one `DataPlot` connected to several `Droplets`. Thanks.

**Comment by tazzaoui** [comment]
We should be able to fix this by replacing multithreading with multiprocessing. Will push a fix shortly

**Comment by dealmeidavf** [comment]
This problem is now solve temporarily with [this function] (https://github.com/dpploy/cortix/blob/1c4602f9828d39cf80eaadab2e00db3683e174df/cortix/util/dataplot.py#L42-L43) and corresponding mods.

**Comment by tazzaoui** [comment]
Looping over the ports is a good idea. Let's remove the old plotting function then.
