### ISSUE TITLE
How to connect multiple ports to one module

### ISSUE THREAD

**Issue by seamuss1** [dpploy/cortix#179]
How do you connect multiple ports to one module? There seems to be a bug with `Port.connect(Port)` where only the most recently called connection is saved.

Example of bug:
https://github.com/dpploy/dados/blob/seamus/src/dados.py
If you were to switch the order of line 22 and line 23, then rs232 can't communicate with plotting anymore but mcc118 can. Any idea what is causing the issue?

**Comment by tazzaoui** [comment]
This is not a bug, aport can only be connected to one other port (see the Port class). When you call connect the second time it overrites the first one. This is to mimick point to point communication.

To accompish what you're trying to do, just create another port like so:

````
p1 = Port('rs')
p2 = Port('mcc')

p3 = Port('rs-plot')
p4 = Port('mcc-plot')

p1.connect(p3)
p2.connect(p4)
```

**Comment by seamuss1** [comment]
And what do you do after connecting the ports?
```

self.rs232.add_port(p1)                                                                                                                                                 self.mcc118.add_port(p2)                                                                                                                                                self.plot.add_port(p3)                                                                                                                                                  self.plot.add_port(p4) 

```
Like that?

**Comment by seamuss1** [comment]
Is this how you get the port objects and send/receive messages?

Sending module:
```
rs = self.get_port('rs-plot')
self.senf('test message', rs)

```

Receiving module:
'''

rs = self.get_port('rs')
line = self.recv(rs)

'''

**Comment by tazzaoui** [comment]
Yes. You can also do 

```
self.send('test message', 'rs-plot')
```

and

```
line = self.recv('rs')
```

directly.

**Comment by seamuss1** [comment]
Oh that's more convenient. It would be nice if the port object was passed into the module so you would not have to call for it or enter the string identifier.
