### ISSUE TITLE
All MPI processes have a copy of the entire network

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#187]
https://github.com/dpploy/cortix/blob/dc1b401bba1a6e9211b30703a413006a517c3cb5/cortix/src/cortix_main.py#L38

By doing this, every MPI process has a copy of the entire network. When running say a 1000-module network case, the total number of instances of modules is 1,000,000. Maybe this requires some thought...scaling becomes an issue.

**Comment by tazzaoui** [comment]
As of right now this is necessary as each rank will know which module to run by looping over all modules and running the one that corresponds to the rank's index. 

We can probably get around this by doing module assignment in `add_module` instead of `run`.

**Comment by dealmeidavf** [comment]
This is an old graph partition problem. Either rank 0 builds the whole graph and partitions it to the other ranks, or all ranks read a piece of the graph sitting out of core. Since most cores are powerful enough, we may go with the former.

**Comment by tazzaoui** [comment]
It isn't so much a graph as it is a list of modules. When we call `add_module` every rank adds that module to its list of modules.  If dynamic spawning worked well in `mpi4py` we could avoid doing this altogether and just spawn a processes as needed, however it isn't that simple. 

We could keep some sort of module counter and have ranks add the module only if the index matches with its rank. This would solve the issue by essentially moving the logic in `run` one level higher.

**Comment by dealmeidavf** [comment]
`mpi4py` has [`mpi4py.futures`](https://mpi4py.readthedocs.io/en/latest/mpi4py.futures.html) which we can use to have a master process to build everything then spawn the workers to run the modules. This works with the `mpiexec` command syntax just as running the conventional MPI execution.

**Comment by tazzaoui** [comment]
What we're really after is dynamic process management (see here: https://mpi4py.readthedocs.io/en/stable/overview.html#dynamic-process-management). 

However, I am not convinced that adding the modules to `self.modules` is a performance hit big enough to warrant the headache of dynamic process management.

**Comment by dealmeidavf** [comment]
As I indicated in my [previous message](https://github.com/dpploy/cortix/issues/187#issuecomment-516046240) the [mpi4py.futures](https://mpi4py.readthedocs.io/en/latest/mpi4py.futures.html) has a section on `MPIPoolExecutor` which says:

    MPIPoolExecutor takes advantage of the dynamic process management features introduced in the MPI-2 standard.

In addition if we use `mpi4py.futures` the code will look very much as a Python multiprocessing syntax.
