### ISSUE TITLE
add_module() design

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#188]
https://github.com/dpploy/cortix/blob/dc1b401bba1a6e9211b30703a413006a517c3cb5/cortix/src/cortix_main.py#L54

This design has one issue. The ports of the module must all be set up before this function is called. Therefore the user cannot call the function before ports are wired. This is a reflection of having ports outside the Module class. I would like to be able to add a module to a `Cortix` object at any point in a program, and as the network is built, the module object is updated automatically. The consolidated `run_droplet.py`
https://github.com/dpploy/cortix/blob/979faa6c8fbcf7fd4071decf3ec5a1ca27172eb0/cortix/examples/fluidflow/run_droplet.py#L82
 run file in my branch is an example that does not work.

**Comment by tazzaoui** [comment]
This example also runs without error on my machine. Could you post the specific error code you get when you run it?

**Comment by dealmeidavf** [comment]
This function

https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/cortix_main.py#L75-L87

will not set the `port.rank` if ports have not been added to the module when using MPI. Therefore on my machines (linux and darwin) when running with MPI, if `add_module` is called before `add_port` send and receives do not work. However if I use multiprocessing, it does work. Please verify your machine with MPI. Thanks.
