### ISSUE TITLE
Port rank

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#194]
Is the `rank` here

https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/cortix_main.py#L82-L87

the same as the `rank` member variable in the constructor?

https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/port.py#L28-L30

Or is it overriding it after construction?

**Comment by dealmeidavf** [comment]
Similarly this code L22-26

https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/port.py#L17-L26

should not be here since the decision to use MPI is made at the Cortix configuration level. Once the user decides for MPI, it should be installed otherwise `mpirun` breaks.

**Comment by tazzaoui** [comment]
The rank is initialized in the `Port` constructor to be the rank of the current process. It is overwritten once the module is added to the cortix simulation so that the ports can know which rank to send data to here

https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/port.py#L55

and receive data from here:

https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/port.py#L66

**Comment by tazzaoui** [comment]
Falling back to multiprocessing if an import error is caught after trying to import `mpi4py` makes the package more fault tolerant. It's definitely better to try running with mp before crashing to the user. We should however add a warning to let the user know there's an mpi4py error and we're switching back ends in an effort to be more transparent.

**Comment by dealmeidavf** [comment]
> The rank is initialized in the `Port` constructor to be the rank of the current process. It is overwritten once the module is added to the cortix simulation so that the ports can know which rank to send data to here
> 
> https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/port.py#L55
> 
> and receive data from here:
> 
> https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/port.py#L66

Maybe the initialization here

https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/port.py#L28-L30

 should be: `self.rank = None` to make sure the port gets the proper rank later.

**Comment by tazzaoui** [comment]
Probably not. The rank is only overwritten if the port is added to the module. Ports that aren't used by a module will still need a rank to be able to send and receive data to other ports. Setting their rank to None will essentially make them useless without being attached to a module.

**Comment by dealmeidavf** [comment]
I set it to `None` and ran all cases of the Droplet-Vortex example and all the `rank` variable is assigned later as it should be. If it is not, then there is a problem and the code should stop. I have the setting in the PR submitted.
