### ISSUE TITLE
Module self.rank

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#195]
https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/module.py#L16

`self.rank` is not used anywhere in `Module`. Why is it needed? Probably it is not.

**Comment by tazzaoui** [comment]
It is needed to know which process to send the module to. 

The rank is set here:

https://github.com/dpploy/cortix/blob/ddb5a1002b61afce8bf08fe23118dc88839f793d/cortix/src/cortix_main.py#L85

and used to launch the module here:

https://github.com/dpploy/cortix/blob/master/cortix/src/cortix_main.py#L117

**Comment by dealmeidavf** [comment]
This variable is not used anywhere in the Module class so why have it?

In addition, module `rank` is confusing because all processes have all modules but only one module out a list actually runs. This proposed [PR](https://github.com/dpploy/cortix/pull/196#issue-302777495) does not create an artificial `rank` for every module.

https://github.com/dpploy/cortix/blob/dac4f7525afe2b28d00e755bae9552f9945037f9/cortix/src/cortix_main.py#L98-L103

and the MPI run is as folllows:

https://github.com/dpploy/cortix/blob/dac4f7525afe2b28d00e755bae9552f9945037f9/cortix/src/cortix_main.py#L113-L117
