### ISSUE TITLE
modules list data lost when in multiprocessing mode

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#199]
In this block:

https://github.com/dpploy/cortix/blob/f65005fd1494f724aa7fb610af6b32e3f0ffee87/cortix/src/cortix_main.py#L131-L138

`p = Process(target=mod.run) ` copies the `mod` object onto the child process. The data is frozen at that time and when the child process ends, the data is lost. The `modules` list in the parent process needs to get that data for all child process so the `Cortix` object can offer the caller access to the data in the `mod` objects as created by the child process. A chief use of that is when running a Jupyter notebook Cortix app. Once `cortix.run()` finishes the user can do `cortix.modules` and access all the data computed in parallel for plotting purposes (say); a very useful feature.

**Comment by tazzaoui** [comment]
The data isn't really getting lost, it is just that when a module is launched on its own process, it operates in its own separate address space meaning the changes it makes to its own data will not be reflected in the main process.

The way around this is to use something like a [Queue](https://docs.python.org/3/library/queue.html#Queue.Queue) or a [Manager](https://docs.python.org/3/library/multiprocessing.html#managers) to copy over the module data when it finishes the run. 

The quick and dirty way would obviously be to just pickle the module before exiting and read it back after for analysis.

**Comment by dealmeidavf** [comment]
This is in the PR and works partially

https://github.com/dpploy/cortix/blob/d65f5f534a0c432d74b16ada0854b235945c66a2/cortix/src/cortix_main.py#L141-L158

but there is an issue with putting non-pickle-able objects in a queue.

**Comment by tazzaoui** [comment]
Why is the pickling done on the DataPlot side rather than the Droplet/Vortex side?

**Comment by dealmeidavf** [comment]
This change in the multiprocessing `cortix.run()` method

https://github.com/dpploy/cortix/blob/c64280de4c63eb1a9a8b487b5d84f5273efb6a9e/cortix/src/cortix_main.py#L137-L160

does the trick of allowing modules data access through the cortix object. In particular this is very useful on notebooks. However, this has introduced some mods that will not stay. Let's discuss the experience. Note `run_droplet.ipynb` test in the `cortix-nb` repo.
