### ISSUE TITLE
network graph with arrows

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#202]
It would be really insightful to have arrows on the network graph to denote whether an edge is used both ways. This helps understanding the flow of information. For instance see graph in

https://nbviewer.jupyter.org/github/dpploy/cortix-nb/blob/master/run_justice.ipynb#Verify-the-network-connectivity

not all edges have bidirectional information.

**Comment by tazzaoui** [comment]
The information flow through a set of ports is bidirectional, which makes Cortix network graphs undirected. Displaying a directed graph would imply that information flows in a specific direction which isn't the case.

**Comment by dealmeidavf** [comment]
Did you see the graph in the link above? From Parole to Prison, there is information both ways. From Adjudication to Prison is only one way. An arrow there would indicate how the edge is using in the actual simulation.

**Comment by tazzaoui** [comment]
I did. However to even gather that information, we would have to analyze the communication during the run to keep track of the flow of information between each module

**Comment by dealmeidavf** [comment]
It could be something simple; maybe an additional flag from the module on the intent of communication. Sure there is almost always a send and a receive (so it is bidirectional; exceptions exist: DataPlot only issues a receive; never a send) but the primary information may go in one direction or another or both. It is insight of the simulation that would be useful. I can bet the first question I will get on that graph is whether populations go both ways everywhere.

**Comment by dealmeidavf** [comment]
This is an area that could really help the user:

https://nbviewer.jupyter.org/github/dpploy/cortix-nb/blob/master/run_justice.ipynb#Verify-the-network-connectivity

Catching the customer by the eye! The above graph could be greatly improved with arrows and a more structured way to give a better sense of the "flow of domain information." Not the actual sends and receives under the hood.

**Comment by dealmeidavf** [comment]
Now handled by the network class method:

https://github.com/dpploy/cortix/blob/f365c8c138fcf580006bc86cdd8d9d73bf4698da/cortix/src/network.py#L272-L301

This uses graphviz and there are lots of options we can explore to improve the graph view.
