### ISSUE TITLE
Overflow of processes while using Cortix in a loop

### ISSUE THREAD

**Issue by seamuss1** [dpploy/cortix#226]
Hi,
A Multiprocessing error is returned whenever more processes are open than the system can handle, which is:
`OSError: [Errno 24] Too many open files`
I'm not sure what triggers the exception. It could possibly be hardware dependent, but this behavior is expected.

However, this error also triggers while placing a Cortix simulation within a loop. It appears some processes carry over into the rest of the python program even though they are not needed. Is there anyway Cortix can handle ending processes better?

Use case:
```
n_list = [15,30,45,60,75,500,600,1200,2400,3200,4200,5400]
for i in n_list:
    procs = 15
    runtime=0.5
    balls = int(i/procs)
    cortix = Cortix(use_mpi=False)
    mod_list = []
    shape = geo.box(-30,0,30,50)
    
    plot = Plot(number=i,runtime=runtime)
    cortix.add_module(plot)

    for i in range(procs):
        time.sleep(0.01)
        app = BallHandler(shape, balls=balls,runtime = runtime)
        app.v0 = [40,40]
        app.r = 0.1
        mod_list.append(app)
        cortix.add_module(app)
        
    for c,i in enumerate(mod_list):
        i.connect('plot-send{}'.format(c),plot.get_port('plot-receive{}'.format(c)))
        for j in mod_list:
            if i == j:
                continue
            name = '{}{}'.format(i.timestamp,j.timestamp)
            name2 = '{}{}'.format(j.timestamp,i.timestamp)
            j.connect(name, i.get_port(name2))
            
    cortix.run()

```
After about 3 loops the program crashes. Each individual loop would be fine, but they can't be run subsequently.

**Comment by dealmeidavf** [comment]
Do your modules start any multiprocessing process?

We have a `close()` function in Cortix now to call at the end of the program:   

    `cortix.close()` 

at the moment this function does not close all it needs to but it is a place to do that. Or in the `run()` method, the processes should all be finished.

Could you point me to your repo and what to download to run on my machine?

**Comment by dealmeidavf** [comment]
Could you try with mpi?

**Comment by seamuss1** [comment]
Actually it works fine with mpi, the bug is with multiprocessing. It might be solved, can @tazzaoui weigh in?

There was excessive Queue objects being created, 2 for each connection when only one was necessary. This improved performance but did not necessarily resolve the initial issue of memory carry-over.

**Comment by tazzaoui** [comment]
Checkout the fix I pushed that uses Pipes rather than Queues in my branch. Does your code still have the same errors?

**Comment by seamuss1** [comment]
@tazzaoui The changes to pipes seems to speed up the simulation speed in general. Very good change from Queues to Pipes, since communication seems to be the bottleneck in run times

Also definitely improves the memory-carry over issue, but does not eliminate it. See the error code below. A few commits ago Cortix could not run a simulation past the 2nd iteration

```
7 iterations
Traceback (most recent call last):
  File "small_ball_test.py", line 351, in <module>
    sim.run()
  File "small_ball_test.py", line 340, in run
    self.net.connect([i,name], [j,name2])
  File "/home/pi/cortix/cortix/src/network.py", line 178, in connect
    port_a.connect(port_b)
  File "/home/pi/cortix/cortix/src/port.py", line 70, in connect
    (self.pipe, port.pipe) = Pipe()
  File "/usr/lib/python3.7/multiprocessing/context.py", line 62, in Pipe
    return Pipe(duplex)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 511, in Pipe
    s1, s2 = socket.socketpair()
  File "/usr/lib/python3.7/socket.py", line 491, in socketpair
    a, b = _socket.socketpair(family, type, proto)
OSError: [Errno 24] Too many open files
```

**Comment by tazzaoui** [comment]
Marking this as solved for now by moving to Pipes. 

In general, multiprocessing mode is very limited in comparison with MPI. Codes that are a bit more computationally intense should be using MPI anyway.
