### ISSUE TITLE
Headers maintenance

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#25]
Please help add the same header to every file in Cortix. I have started but we need to keep an eye open and fix the files as we go. Use one of the files in the src/ directory as a model.

**Comment by tazzaoui** [comment]
Shouldn't the first line of the header be ```#!/usr/bin/env python```? Otherwise, the driver can't be invoked without the python command

**Comment by dealmeidavf** [comment]
Yes. It probably was delete by accident.

**Comment by dealmeidavf** [comment]
You have been warned.
