### ISSUE TITLE
Why only shutdown parameters are used? how about startup?

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#269]
https://github.com/dpploy/cortix/blob/0b1474d84533aed208567bf36421fe6f96aaa492/cortix/examples/bwr/run_plant.py#L49-L50

**Comment by arotker45** [comment]
I want to display behavior during startup, shutdown and steady-state operation. It is easiest to do this all in just run rather than having separate startup and shutdown scenarios, so for now only the shutdown parameters are used.

**Comment by arotker45** [comment]
Because the current "shutdown scenario" already includes startup and steady-state operation.

**Comment by dealmeidavf** [comment]
A better logic is to run up to steady state. Look at results. Then invoke run again and shutdown. This requires a continuation of the previous run state.

**Comment by dealmeidavf** [comment]
> Because the current "shutdown scenario" already includes startup and steady-state operation.

This https://github.com/dpploy/cortix/blob/b88e29b4f1acbec99561d86a52823cf264efc18a/cortix/examples/bwr/startup_params.py#L2 is not used anywhere.

A full cleanup of this code is needed; it is now an example in the master branch.

**Comment by dealmeidavf** [comment]
Most of `params` has been removed. The pending parameters will be addressed on a case by case basis.
