### ISSUE TITLE
pytest failures

### ISSUE THREAD

**Issue by dealmeidavf** [dpploy/cortix#32]
[screen.txt](https://github.com/dpploy/cortix/files/2320302/screen.txt)

**Comment by tazzaoui** [comment]
The issue here is that the path to ```cortix-config.xml``` is different for everybody.  We need to add a separate examples directory specific to the tests with a hard-coded config file. Will push a fix for this shortly

**Comment by tazzaoui** [comment]
Problem should be fixed as of #39 . WIll re-open if issue arises again
